# Generated by Django 4.0.3 on 2022-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0002_alter_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
